Repository rit-coms/COMS-Console, pull requests merged in 2025-04, with the labels that each got.

#36 Make usernames unique
  src-tauri/migrations/2025-02-21-211725_create_users/up.sql
  src-tauri/src/db/mod.rs
  src-tauri/src/db/models.rs
  src-tauri/src/db/schema.rs
  src-tauri/tests/integration_tests.rs
Labels: feature

#30 Refactor Get Games
  src-tauri/src/db/mod.rs
  src-tauri/src/frontend_api/mod.rs
Labels: feature

#38 Tauri command for leaderboard data
  src-tauri/migrations/2025-02-21-043342_create_leaderboard/up.sql
  src-tauri/migrations/2025-02-21-211832_create_saves/up.sql
  src-tauri/src/db/mod.rs
  src-tauri/src/db/models.rs
  src-tauri/src/db/schema.rs
  src-tauri/src/db/test_context.rs
  src-tauri/src/frontend_api/mod.rs
  src-tauri/src/game_dev_api/handlers.rs
  src-tauri/src/main.rs
  src-tauri/tests/integration_tests.rs
Labels: feature

#49 Dev/fix game dev api
  src-tauri/migrations/2025-02-21-043342_create_leaderboard/up.sql
  src-tauri/migrations/2025-02-21-211832_create_saves/up.sql
  src-tauri/src/db/mod.rs
  src-tauri/src/db/models.rs
  src-tauri/src/db/test_context.rs
  src-tauri/src/frontend_api/mod.rs
  src-tauri/src/game_dev_api/handlers.rs
  src-tauri/src/game_dev_api/mod.rs
  src-tauri/src/main.rs
  src-tauri/tests/integration_tests.rs
Labels: bug

#51 Update Cargo.toml
  src-tauri/Cargo.lock
  src-tauri/Cargo.toml
  src-tauri/src/frontend_api/mod.rs
  src-tauri/src/game_dev_api/mod.rs
  src-tauri/tests/integration_tests.rs
Labels: documentation

#54 Run embedded migrations
  src-tauri/src/db/mod.rs
  src-tauri/src/main.rs
Labels: bug

#48 Add Current Game
  src-tauri/Cargo.lock
  src-tauri/migrations/2025-02-21-043342_create_leaderboard/up.sql
  src-tauri/src/db/mod.rs
  src-tauri/src/db/test_context.rs
  src-tauri/src/frontend_api/mod.rs
  src-tauri/src/game_dev_api/handlers.rs
  src-tauri/src/game_dev_api/mod.rs
  src-tauri/src/main.rs
  src-tauri/tests/integration_tests.rs
Labels: feature

#31 Update Templates for Issues and PRs
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/task_create.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#62 CI/CD fixes for the V1 Release
  .github/workflows/main.yml
  .github/workflows/pi.yml
  .github/workflows/rust.yml
  src-tauri/tauri.conf.json
Labels: dev-qol
